"""
Pytest suite verifying runtime requirements, performance metrics,
and operational validation logs generated by the ML serving codebase.
"""

import os
import json
import subprocess
import pytest

def run_benchmark_harness():
    """Helper execution tracking to guarantee standard metric baseline generation."""
    cmd = ["python3", "/app/project/benchmark.py"]
    subprocess.run(cmd, check=True)
    metrics_path = "/app/project/logs/metrics.json"
    assert os.path.exists(metrics_path), "Operational benchmark failed to emit metrics payload."
    with open(metrics_path, "r") as f:
        return json.load(f)

def test_throughput_performance():
    """Verify that the system architecture achieves a throughput performance profile >= 50 req/sec."""
    metrics = run_benchmark_harness()
    assert metrics["throughput"] >= 50.0, f"System throughput underperformed at {metrics['throughput']} req/sec."

def test_p99_latency_bounds():
    """Ensure p99 latency does not degrade beyond the 150ms service level objective."""
    metrics = run_benchmark_harness()
    assert metrics["p99_latency_ms"] <= 150.0, f"Catastrophic latency spike observed: {metrics['p99_latency_ms']} ms."

def test_zero_scheduler_starvation():
    """Ensure scheduler optimization completely eliminates queue starvation events."""
    metrics = run_benchmark_harness()
    assert metrics["starvation_events"] == 0, f"Regressive behavior detected: {metrics['starvation_events']} starvation instances found."

def test_speculative_routing_utilization():
    """Verify that speculative routing paths are successfully utilized by matching eligible trace requests."""
    metrics = run_benchmark_harness()
    assert metrics["speculative_routes"] > 50, "Speculative track routing engine failed to balance transaction load."